
#include "Mix4.hpp"

#define POLY_OFFSET "poly_channel_offset"

json_t* Mix4::dataToJson() {
	json_t* root = json_object();
	json_object_set_new(root, POLY_OFFSET, json_integer(_polyChannelOffset));
	return root;
}

void Mix4::dataFromJson(json_t* root) {
	json_t* o = json_object_get(root, POLY_OFFSET);
	if (o) {
		_polyChannelOffset = json_integer_value(o);
	}
}

void Mix4::sampleRateChange() {
	float sr = APP->engine->getSampleRate();
	for (int i = 0; i < 4; ++i) {
		_channels[i]->setSampleRate(sr);
		_panSLs[i].setParams(sr, MIXER_PAN_SLEW_MS, 2.0f);
	}
	_slewLimiter.setParams(sr, MixerChannel::levelSlewTimeMS, MixerChannel::maxDecibels - MixerChannel::minDecibels);
	_rms.setSampleRate(sr);
}

void Mix4::processAll(const ProcessArgs& args) {
	Mix4ExpanderMessage* toExp = &_dummyExpanderMessage;
	Mix4ExpanderMessage* fromExp = &_dummyExpanderMessage;
	if (connected()) {
		toExp = toExpander();
		fromExp = fromExpander();
	}

	bool solo =
		params[MUTE1_PARAM].getValue() > 1.5f ||
		params[MUTE2_PARAM].getValue() > 1.5f ||
		params[MUTE3_PARAM].getValue() > 1.5f ||
		params[MUTE4_PARAM].getValue() > 1.5f;

	{
		float sample = 0.0f;
		if (_polyChannelOffset >= 0) {
			sample = inputs[IN1_INPUT].getPolyVoltage(_polyChannelOffset);
		} else {
			sample = inputs[IN1_INPUT].getVoltageSum();
		}
		_channels[0]->next(sample, solo);
		toExp->preFader[0] = sample;

		for (int i = 1; i < 4; ++i) {
			float sample = 0.0f;
			if (inputs[IN1_INPUT + 3 * i].isConnected()) {
				sample = inputs[IN1_INPUT + 3 * i].getVoltageSum();
			}
			else if (_polyChannelOffset >= 0) {
				sample = inputs[IN1_INPUT].getPolyVoltage(_polyChannelOffset + i);
			}
			_channels[i]->next(sample, solo);
			toExp->preFader[i] = sample;
		}
	}

	float level = Amplifier::minDecibels;
	if (params[MIX_MUTE_PARAM].getValue() < 0.5f) {
		level = params[MIX_PARAM].getValue();
		if (inputs[MIX_CV_INPUT].isConnected()) {
			level *= clamp(inputs[MIX_CV_INPUT].getVoltage() / 10.0f, 0.0f, 1.0f);
		}
		level *= MixerChannel::maxDecibels - MixerChannel::minDecibels;
		level += MixerChannel::minDecibels;
	}
	_amplifier.setLevel(_slewLimiter.next(level));

	float outs[4];
	for (int i = 0; i < 4; ++i) {
		toExp->postFader[i] = outs[i] = _channels[i]->out;
	}

	float mono = 0.0f;
	float left = 0.0f;
	float right = 0.0f;
	if (connected()) {
		mono += fromExp->returnA[0] + fromExp->returnB[0];
		left += fromExp->returnA[0] + fromExp->returnB[0];
		right += fromExp->returnA[1] + fromExp->returnB[1];
		std::copy(fromExp->postEQ, fromExp->postEQ + 4, outs);
	}

	for (int i = 0; i < 4; ++i) {
		mono += outs[i];
	}
	mono = _amplifier.next(mono);
	mono = _saturator.next(mono);
	_rmsLevel = _rms.next(mono) / 5.0f;

	if (outputs[L_OUTPUT].isConnected() && outputs[R_OUTPUT].isConnected()) {
		for (int i = 0; i < 4; ++i) {
			float pan = clamp(params[PAN1_PARAM + 3 * i].getValue(), -1.0f, 1.0f);
			if (inputs[PAN1_INPUT + 3 * i].isConnected()) {
				pan *= clamp(inputs[PAN1_INPUT + 3 * i].getVoltage() / 5.0f, -1.0f, 1.0f);
			}
			_panners[i].setPan(_panSLs[i].next(pan));
			float l, r;
			_panners[i].next(outs[i], l, r);
			left += l;
			right += r;
		}

		left = _amplifier.next(left);
		left = _saturator.next(left);
		outputs[L_OUTPUT].setVoltage(left);

		right = _amplifier.next(right);
		right = _saturator.next(right);
		outputs[R_OUTPUT].setVoltage(right);
	}
	else {
		outputs[L_OUTPUT].setVoltage(mono);
		outputs[R_OUTPUT].setVoltage(mono);
	}
}

struct Mix4Widget : ModuleWidget {
	static constexpr int hp = 15;

	Mix4Widget(Mix4* module) {
		setModule(module);
		box.size = Vec(RACK_GRID_WIDTH * hp, RACK_GRID_HEIGHT);

		{
			SvgPanel *panel = new SvgPanel();
			panel->box.size = box.size;
			panel->setBackground(APP->window->loadSvg(asset::plugin(pluginInstance, "res/Mix4.svg")));
			addChild(panel);
		}

		addChild(createWidget<ScrewSilver>(Vec(15, 0)));
		addChild(createWidget<ScrewSilver>(Vec(box.size.x - 30, 0)));
		addChild(createWidget<ScrewSilver>(Vec(15, 365)));
		addChild(createWidget<ScrewSilver>(Vec(box.size.x - 30, 365)));

		// generated by svg_widgets.rb
		auto level1ParamPosition = Vec(17.5, 32.0);
		auto mute1ParamPosition = Vec(17.2, 185.7);
		auto pan1ParamPosition = Vec(18.5, 223.0);
		auto level2ParamPosition = Vec(60.5, 32.0);
		auto mute2ParamPosition = Vec(60.2, 185.7);
		auto pan2ParamPosition = Vec(61.5, 223.0);
		auto level3ParamPosition = Vec(103.5, 32.0);
		auto mute3ParamPosition = Vec(103.2, 185.7);
		auto pan3ParamPosition = Vec(104.5, 223.0);
		auto level4ParamPosition = Vec(146.5, 32.0);
		auto mute4ParamPosition = Vec(146.2, 185.7);
		auto pan4ParamPosition = Vec(147.5, 223.0);
		auto mixParamPosition = Vec(189.5, 32.0);
		auto mixMuteParamPosition = Vec(189.2, 185.7);

		auto cv1InputPosition = Vec(14.5, 255.0);
		auto pan1InputPosition = Vec(14.5, 290.0);
		auto in1InputPosition = Vec(14.5, 325.0);
		auto cv2InputPosition = Vec(57.5, 255.0);
		auto pan2InputPosition = Vec(57.5, 290.0);
		auto in2InputPosition = Vec(57.5, 325.0);
		auto cv3InputPosition = Vec(100.5, 255.0);
		auto pan3InputPosition = Vec(100.5, 290.0);
		auto in3InputPosition = Vec(100.5, 325.0);
		auto cv4InputPosition = Vec(143.5, 255.0);
		auto pan4InputPosition = Vec(143.5, 290.0);
		auto in4InputPosition = Vec(143.5, 325.0);
		auto mixCvInputPosition = Vec(186.5, 252.0);

		auto lOutputPosition = Vec(186.5, 290.0);
		auto rOutputPosition = Vec(186.5, 325.0);
		// end generated by svg_widgets.rb

		addSlider(level1ParamPosition, module, Mix4::LEVEL1_PARAM, module ? &module->_channels[0]->rms : NULL);
		addParam(createParam<Knob16>(pan1ParamPosition, module, Mix4::PAN1_PARAM));
		addParam(createParam<SoloMuteButton>(mute1ParamPosition, module, Mix4::MUTE1_PARAM));
		addSlider(level2ParamPosition, module, Mix4::LEVEL2_PARAM, module ? &module->_channels[1]->rms : NULL);
		addParam(createParam<Knob16>(pan2ParamPosition, module, Mix4::PAN2_PARAM));
		addParam(createParam<SoloMuteButton>(mute2ParamPosition, module, Mix4::MUTE2_PARAM));
		addSlider(level3ParamPosition, module, Mix4::LEVEL3_PARAM, module ? &module->_channels[2]->rms : NULL);
		addParam(createParam<Knob16>(pan3ParamPosition, module, Mix4::PAN3_PARAM));
		addParam(createParam<SoloMuteButton>(mute3ParamPosition, module, Mix4::MUTE3_PARAM));
		addSlider(level4ParamPosition, module, Mix4::LEVEL4_PARAM, module ? &module->_channels[3]->rms : NULL);
		addParam(createParam<Knob16>(pan4ParamPosition, module, Mix4::PAN4_PARAM));
		addParam(createParam<SoloMuteButton>(mute4ParamPosition, module, Mix4::MUTE4_PARAM));
		addSlider(mixParamPosition, module, Mix4::MIX_PARAM, module ? &module->_rmsLevel : NULL);
		addParam(createParam<MuteButton>(mixMuteParamPosition, module, Mix4::MIX_MUTE_PARAM));

		addInput(createInput<Port24>(cv1InputPosition, module, Mix4::CV1_INPUT));
		addInput(createInput<Port24>(pan1InputPosition, module, Mix4::PAN1_INPUT));
		addInput(createInput<Port24>(in1InputPosition, module, Mix4::IN1_INPUT));
		addInput(createInput<Port24>(cv2InputPosition, module, Mix4::CV2_INPUT));
		addInput(createInput<Port24>(pan2InputPosition, module, Mix4::PAN2_INPUT));
		addInput(createInput<Port24>(in2InputPosition, module, Mix4::IN2_INPUT));
		addInput(createInput<Port24>(cv3InputPosition, module, Mix4::CV3_INPUT));
		addInput(createInput<Port24>(pan3InputPosition, module, Mix4::PAN3_INPUT));
		addInput(createInput<Port24>(in3InputPosition, module, Mix4::IN3_INPUT));
		addInput(createInput<Port24>(cv4InputPosition, module, Mix4::CV4_INPUT));
		addInput(createInput<Port24>(pan4InputPosition, module, Mix4::PAN4_INPUT));
		addInput(createInput<Port24>(in4InputPosition, module, Mix4::IN4_INPUT));
		addInput(createInput<Port24>(mixCvInputPosition, module, Mix4::MIX_CV_INPUT));

		addOutput(createOutput<Port24>(lOutputPosition, module, Mix4::L_OUTPUT));
		addOutput(createOutput<Port24>(rOutputPosition, module, Mix4::R_OUTPUT));
	}

	void addSlider(Vec position, Mix4* module, int id, float* rms) {
		auto slider = createParam<VUSlider151>(position, module, id);
		if (rms) {
			dynamic_cast<VUSlider*>(slider)->setVULevel(rms);
		}
		addParam(slider);
	}

	void appendContextMenu(Menu* menu) override {
		Mix4* m = dynamic_cast<Mix4*>(module);
		assert(m);
		menu->addChild(new MenuLabel());
		OptionsMenuItem* mi = new OptionsMenuItem("Input 1 poly spread");
		mi->addItem(OptionMenuItem("None", [m]() { return m->_polyChannelOffset == -1; }, [m]() { m->_polyChannelOffset = -1; }));
		mi->addItem(OptionMenuItem("Channels 1-4", [m]() { return m->_polyChannelOffset == 0; }, [m]() { m->_polyChannelOffset = 0; }));
		mi->addItem(OptionMenuItem("Channels 5-8", [m]() { return m->_polyChannelOffset == 4; }, [m]() { m->_polyChannelOffset = 4; }));
		mi->addItem(OptionMenuItem("Channels 9-12", [m]() { return m->_polyChannelOffset == 8; }, [m]() { m->_polyChannelOffset = 8; }));
		mi->addItem(OptionMenuItem("Channels 13-16", [m]() { return m->_polyChannelOffset == 12; }, [m]() { m->_polyChannelOffset = 12; }));
		OptionsMenuItem::addToMenu(mi, menu);
	}
};

Model* modelMix4 = bogaudio::createModel<Mix4, Mix4Widget>("Bogaudio-Mix4", "MIX4", "4-channel mixer and panner", "Mixer", "Panning");


void Mix4x::sampleRateChange() {
	float sr = APP->engine->getSampleRate();
	for (int i = 0; i < 4; ++i) {
		_channels[i]->setSampleRate(sr);
	}
	_returnASL.setParams(sr, MixerChannel::levelSlewTimeMS, MixerChannel::maxDecibels - MixerChannel::minDecibels);
	_returnBSL.setParams(sr, MixerChannel::levelSlewTimeMS, MixerChannel::maxDecibels - MixerChannel::minDecibels);
}

void Mix4x::processAll(const ProcessArgs& args) {
	if (!connected()) {
		outputs[SEND_A_OUTPUT].setVoltage(0.0f);
		outputs[SEND_B_OUTPUT].setVoltage(0.0f);
		return;
	}

	Mix4ExpanderMessage* from = fromBase();
	Mix4ExpanderMessage* to = toBase();
	float sendA = 0.0f;
	float sendB = 0.0f;
	for (int i = 0; i < 4; ++i) {
		_channels[i]->next(from->preFader[i], from->postFader[i]);
		to->postEQ[i] = _channels[i]->postEQ;
		sendA += _channels[i]->sendA;
		sendB += _channels[i]->sendB;
	}
	outputs[SEND_A_OUTPUT].setVoltage(_saturatorA.next(sendA));
	outputs[SEND_B_OUTPUT].setVoltage(_saturatorA.next(sendB));

	float levelA = clamp(params[LEVEL_A_PARAM].getValue(), 0.0f, 1.0f);
	if (inputs[LEVEL_A_INPUT].isConnected()) {
		levelA *= clamp(inputs[LEVEL_A_INPUT].getVoltage() / 10.0f, 0.0f, 1.0f);
	}
	levelA = 1.0f - levelA;
	levelA *= Amplifier::minDecibels;
	_returnAAmp.setLevel(_returnASL.next(levelA));
	if (inputs[L_A_INPUT].isConnected()) {
		to->returnA[0] = _returnAAmp.next(inputs[L_A_INPUT].getVoltage());
	}
	else {
		to->returnA[0] = 0.0f;
	}
	if (inputs[R_A_INPUT].isConnected()) {
		to->returnA[1] = _returnAAmp.next(inputs[R_A_INPUT].getVoltage());
	}
	else {
		to->returnA[1] = to->returnA[0];
	}

	float levelB = clamp(params[LEVEL_B_PARAM].getValue(), 0.0f, 1.0f);
	levelB = 1.0f - levelB;
	levelB *= Amplifier::minDecibels;
	_returnBAmp.setLevel(_returnBSL.next(levelB));
	if (inputs[L_B_INPUT].isConnected()) {
		to->returnB[0] = _returnBAmp.next(inputs[L_B_INPUT].getVoltage());
	}
	else {
		to->returnB[0] = 0.0f;
	}
	if (inputs[R_B_INPUT].isConnected()) {
		to->returnB[1] = _returnBAmp.next(inputs[R_B_INPUT].getVoltage());
	}
	else {
		to->returnB[1] = to->returnB[0];
	}
}

struct Mix4xWidget : ModuleWidget {
	static constexpr int hp = 15;

	Mix4xWidget(Mix4x* module) {
		setModule(module);
		box.size = Vec(RACK_GRID_WIDTH * hp, RACK_GRID_HEIGHT);

		{
			SvgPanel *panel = new SvgPanel();
			panel->box.size = box.size;
			panel->setBackground(APP->window->loadSvg(asset::plugin(pluginInstance, "res/Mix4x.svg")));
			addChild(panel);
		}

		addChild(createWidget<ScrewSilver>(Vec(15, 0)));
		addChild(createWidget<ScrewSilver>(Vec(box.size.x - 30, 0)));
		addChild(createWidget<ScrewSilver>(Vec(15, 365)));
		addChild(createWidget<ScrewSilver>(Vec(box.size.x - 30, 365)));

		// generated by svg_widgets.rb
		auto low1ParamPosition = Vec(18.5, 43.0);
		auto mid1ParamPosition = Vec(18.5, 89.0);
		auto high1ParamPosition = Vec(18.5, 135.0);
		auto a1ParamPosition = Vec(18.5, 180.0);
		auto preA1ParamPosition = Vec(30.0, 208.0);
		auto b1ParamPosition = Vec(18.5, 236.0);
		auto preB1ParamPosition = Vec(30.0, 264.0);
		auto low2ParamPosition = Vec(61.5, 43.0);
		auto mid2ParamPosition = Vec(61.5, 89.0);
		auto high2ParamPosition = Vec(61.5, 135.0);
		auto a2ParamPosition = Vec(61.5, 180.0);
		auto preA2ParamPosition = Vec(73.0, 208.0);
		auto b2ParamPosition = Vec(61.5, 236.0);
		auto preB2ParamPosition = Vec(73.0, 264.0);
		auto low3ParamPosition = Vec(104.5, 43.0);
		auto mid3ParamPosition = Vec(104.5, 89.0);
		auto high3ParamPosition = Vec(104.5, 135.0);
		auto a3ParamPosition = Vec(104.5, 180.0);
		auto preA3ParamPosition = Vec(116.0, 208.0);
		auto b3ParamPosition = Vec(104.5, 236.0);
		auto preB3ParamPosition = Vec(116.0, 264.0);
		auto low4ParamPosition = Vec(147.5, 43.0);
		auto mid4ParamPosition = Vec(147.5, 89.0);
		auto high4ParamPosition = Vec(147.5, 135.0);
		auto a4ParamPosition = Vec(147.5, 180.0);
		auto preA4ParamPosition = Vec(159.0, 208.0);
		auto b4ParamPosition = Vec(147.5, 236.0);
		auto preB4ParamPosition = Vec(159.0, 264.0);
		auto levelAParamPosition = Vec(190.5, 138.0);
		auto levelBParamPosition = Vec(190.5, 328.0);

		auto a1InputPosition = Vec(14.5, 290.0);
		auto b1InputPosition = Vec(14.5, 325.0);
		auto a2InputPosition = Vec(57.5, 290.0);
		auto b2InputPosition = Vec(57.5, 325.0);
		auto a3InputPosition = Vec(100.5, 290.0);
		auto b3InputPosition = Vec(100.5, 325.0);
		auto a4InputPosition = Vec(143.5, 290.0);
		auto b4InputPosition = Vec(143.5, 325.0);
		auto lAInputPosition = Vec(186.5, 62.0);
		auto rAInputPosition = Vec(186.5, 97.0);
		auto levelAInputPosition = Vec(186.5, 170.0);
		auto lBInputPosition = Vec(186.5, 252.0);
		auto rBInputPosition = Vec(186.5, 287.0);

		auto sendAOutputPosition = Vec(186.5, 24.0);
		auto sendBOutputPosition = Vec(186.5, 214.0);
		// end generated by svg_widgets.rb

		addParam(createParam<Knob16>(low1ParamPosition, module, Mix4x::LOW1_PARAM));
		addParam(createParam<Knob16>(mid1ParamPosition, module, Mix4x::MID1_PARAM));
		addParam(createParam<Knob16>(high1ParamPosition, module, Mix4x::HIGH1_PARAM));
		addParam(createParam<Knob16>(a1ParamPosition, module, Mix4x::A1_PARAM));
		addParam(createParam<IndicatorButtonGreen9>(preA1ParamPosition, module, Mix4x::PRE_A1_PARAM));
		addParam(createParam<Knob16>(b1ParamPosition, module, Mix4x::B1_PARAM));
		addParam(createParam<IndicatorButtonGreen9>(preB1ParamPosition, module, Mix4x::PRE_B1_PARAM));
		addParam(createParam<Knob16>(low2ParamPosition, module, Mix4x::LOW2_PARAM));
		addParam(createParam<Knob16>(mid2ParamPosition, module, Mix4x::MID2_PARAM));
		addParam(createParam<Knob16>(high2ParamPosition, module, Mix4x::HIGH2_PARAM));
		addParam(createParam<Knob16>(a2ParamPosition, module, Mix4x::A2_PARAM));
		addParam(createParam<IndicatorButtonGreen9>(preA2ParamPosition, module, Mix4x::PRE_A2_PARAM));
		addParam(createParam<Knob16>(b2ParamPosition, module, Mix4x::B2_PARAM));
		addParam(createParam<IndicatorButtonGreen9>(preB2ParamPosition, module, Mix4x::PRE_B2_PARAM));
		addParam(createParam<Knob16>(low3ParamPosition, module, Mix4x::LOW3_PARAM));
		addParam(createParam<Knob16>(mid3ParamPosition, module, Mix4x::MID3_PARAM));
		addParam(createParam<Knob16>(high3ParamPosition, module, Mix4x::HIGH3_PARAM));
		addParam(createParam<Knob16>(a3ParamPosition, module, Mix4x::A3_PARAM));
		addParam(createParam<IndicatorButtonGreen9>(preA3ParamPosition, module, Mix4x::PRE_A3_PARAM));
		addParam(createParam<Knob16>(b3ParamPosition, module, Mix4x::B3_PARAM));
		addParam(createParam<IndicatorButtonGreen9>(preB3ParamPosition, module, Mix4x::PRE_B3_PARAM));
		addParam(createParam<Knob16>(low4ParamPosition, module, Mix4x::LOW4_PARAM));
		addParam(createParam<Knob16>(mid4ParamPosition, module, Mix4x::MID4_PARAM));
		addParam(createParam<Knob16>(high4ParamPosition, module, Mix4x::HIGH4_PARAM));
		addParam(createParam<Knob16>(a4ParamPosition, module, Mix4x::A4_PARAM));
		addParam(createParam<IndicatorButtonGreen9>(preA4ParamPosition, module, Mix4x::PRE_A4_PARAM));
		addParam(createParam<Knob16>(b4ParamPosition, module, Mix4x::B4_PARAM));
		addParam(createParam<IndicatorButtonGreen9>(preB4ParamPosition, module, Mix4x::PRE_B4_PARAM));
		addParam(createParam<Knob16>(levelAParamPosition, module, Mix4x::LEVEL_A_PARAM));
		addParam(createParam<Knob16>(levelBParamPosition, module, Mix4x::LEVEL_B_PARAM));

		addInput(createInput<Port24>(a1InputPosition, module, Mix4x::A1_INPUT));
		addInput(createInput<Port24>(b1InputPosition, module, Mix4x::B1_INPUT));
		addInput(createInput<Port24>(a2InputPosition, module, Mix4x::A2_INPUT));
		addInput(createInput<Port24>(b2InputPosition, module, Mix4x::B2_INPUT));
		addInput(createInput<Port24>(a3InputPosition, module, Mix4x::A3_INPUT));
		addInput(createInput<Port24>(b3InputPosition, module, Mix4x::B3_INPUT));
		addInput(createInput<Port24>(a4InputPosition, module, Mix4x::A4_INPUT));
		addInput(createInput<Port24>(b4InputPosition, module, Mix4x::B4_INPUT));
		addInput(createInput<Port24>(lAInputPosition, module, Mix4x::L_A_INPUT));
		addInput(createInput<Port24>(rAInputPosition, module, Mix4x::R_A_INPUT));
		addInput(createInput<Port24>(levelAInputPosition, module, Mix4x::LEVEL_A_INPUT));
		addInput(createInput<Port24>(lBInputPosition, module, Mix4x::L_B_INPUT));
		addInput(createInput<Port24>(rBInputPosition, module, Mix4x::R_B_INPUT));

		addOutput(createOutput<Port24>(sendAOutputPosition, module, Mix4x::SEND_A_OUTPUT));
		addOutput(createOutput<Port24>(sendBOutputPosition, module, Mix4x::SEND_B_OUTPUT));
	}
};

Model* modelMix4x = createModel<Mix4x, Mix4xWidget>("Bogaudio-Mix4x", "MIX4X", "Expander for MIX4, adds EQs and sends", "Mixer", "Expander");
