
#include "Mult.hpp"

void Mult::process(const ProcessArgs& args) {
	float out = inputs[INA_INPUT].value;
	outputs[OUTA1_OUTPUT].value = out;
	outputs[OUTA2_OUTPUT].value = out;
	outputs[OUTA3_OUTPUT].value = out;

	if (inputs[INB_INPUT].active) {
		out = inputs[INB_INPUT].value;
	}
	outputs[OUTB1_OUTPUT].value = out;
	outputs[OUTB2_OUTPUT].value = out;
	outputs[OUTB3_OUTPUT].value = out;
}

struct MultWidget : ModuleWidget {
	static constexpr int hp = 3;

	MultWidget(Mult* module) : ModuleWidget(module) {
		box.size = Vec(RACK_GRID_WIDTH * hp, RACK_GRID_HEIGHT);

		{
			SVGPanel *panel = new SVGPanel();
			panel->box.size = box.size;
			panel->setBackground(APP->window->loadSvg(asset::plugin(pluginInstance, "res/Mult.svg")));
			addChild(panel);
		}

		addChild(createWidget<ScrewSilver>(Vec(0, 0)));
		addChild(createWidget<ScrewSilver>(Vec(box.size.x - 15, 365)));

		// generated by svg_widgets.rb
		auto inaInputPosition = Vec(10.5, 21.0);
		auto inbInputPosition = Vec(10.5, 181.0);

		auto outa1OutputPosition = Vec(10.5, 62.0);
		auto outa2OutputPosition = Vec(10.5, 92.0);
		auto outa3OutputPosition = Vec(10.5, 122.0);
		auto outb1OutputPosition = Vec(10.5, 222.0);
		auto outb2OutputPosition = Vec(10.5, 252.0);
		auto outb3OutputPosition = Vec(10.5, 282.0);
		// end generated by svg_widgets.rb

		addInput(createPort<Port24>(inaInputPosition, PortWidget::INPUT, module, Mult::INA_INPUT));
		addInput(createPort<Port24>(inbInputPosition, PortWidget::INPUT, module, Mult::INB_INPUT));

		addOutput(createPort<Port24>(outa1OutputPosition, PortWidget::OUTPUT, module, Mult::OUTA1_OUTPUT));
		addOutput(createPort<Port24>(outa2OutputPosition, PortWidget::OUTPUT, module, Mult::OUTA2_OUTPUT));
		addOutput(createPort<Port24>(outa3OutputPosition, PortWidget::OUTPUT, module, Mult::OUTA3_OUTPUT));
		addOutput(createPort<Port24>(outb1OutputPosition, PortWidget::OUTPUT, module, Mult::OUTB1_OUTPUT));
		addOutput(createPort<Port24>(outb2OutputPosition, PortWidget::OUTPUT, module, Mult::OUTB2_OUTPUT));
		addOutput(createPort<Port24>(outb3OutputPosition, PortWidget::OUTPUT, module, Mult::OUTB3_OUTPUT));
	}
};

Model* modelMult = bogaudio::createModel<Mult, MultWidget>("Bogaudio-Mult", "Mult",  "multiple", MULTIPLE_TAG);
