
#include "Offset.hpp"

#define DISABLE_OUTPUT_LIMIT "disableOutputLimit"

json_t* Offset::toJson() {
	json_t* root = json_object();
	json_object_set_new(root, DISABLE_OUTPUT_LIMIT, json_boolean(_disableOutputLimit));
	return root;
}

void Offset::fromJson(json_t* root) {
	json_t* dol = json_object_get(root, DISABLE_OUTPUT_LIMIT);
	if (dol) {
		_disableOutputLimit = json_is_true(dol);
	}
}

void Offset::step() {
	float offset = knobValue(params[OFFSET_PARAM], inputs[OFFSET_INPUT]);
	float scale = knobValue(params[SCALE_PARAM], inputs[SCALE_INPUT]);
	scale = scale < 0.0f ? -pow(scale, 2.0f) : pow(scale, 2.0f);
	scale *= 10.0;

	float out = inputs[IN_INPUT].value;
	out += 10.0f * offset;
	out *= scale;
	if (!_disableOutputLimit) {
		out = clamp(out, -12.0f, 12.0f);
	}
	outputs[OUT_OUTPUT].value = out;
}

float Offset::knobValue(const Param& knob, const Input& cv) const {
	float v = knob.value;
	if (cv.active) {
		v *= clamp(cv.value / 10.0f, -1.0f, 1.0f);
	}
	return v;
}

struct DisableOutputLimitMenuItem : MenuItem {
	Offset* _module;

	DisableOutputLimitMenuItem(Offset* module, const char* label)
	: _module(module)
	{
		this->text = label;
	}

	void onAction(EventAction &e) override {
		_module->_disableOutputLimit = !_module->_disableOutputLimit;
	}

	void step() override {
		rightText = _module->_disableOutputLimit ? "✔" : "";
	}
};

struct OffsetWidget : ModuleWidget {
	static constexpr int hp = 3;

	OffsetWidget(Offset* module) : ModuleWidget(module) {
		box.size = Vec(RACK_GRID_WIDTH * hp, RACK_GRID_HEIGHT);

		{
			SVGPanel *panel = new SVGPanel();
			panel->box.size = box.size;
			panel->setBackground(SVG::load(assetPlugin(plugin, "res/Offset.svg")));
			addChild(panel);
		}

		addChild(Widget::create<ScrewSilver>(Vec(0, 0)));
		addChild(Widget::create<ScrewSilver>(Vec(box.size.x - 15, 365)));

		// generated by svg_widgets.rb
		auto offsetParamPosition = Vec(8.0, 40.0);
		auto scaleParamPosition = Vec(8.0, 152.0);

		auto offsetInputPosition = Vec(10.5, 81.0);
		auto scaleInputPosition = Vec(10.5, 193.0);
		auto inInputPosition = Vec(10.5, 243.0);

		auto outOutputPosition = Vec(10.5, 281.0);
		// end generated by svg_widgets.rb

		addParam(ParamWidget::create<Knob29>(offsetParamPosition, module, Offset::OFFSET_PARAM, -1.0, 1.0, 0.0));
		addParam(ParamWidget::create<Knob29>(scaleParamPosition, module, Offset::SCALE_PARAM, -1.0, 1.0, 0.316));

		addInput(Port::create<Port24>(offsetInputPosition, Port::INPUT, module, Offset::OFFSET_INPUT));
		addInput(Port::create<Port24>(scaleInputPosition, Port::INPUT, module, Offset::SCALE_INPUT));
		addInput(Port::create<Port24>(inInputPosition, Port::INPUT, module, Offset::IN_INPUT));

		addOutput(Port::create<Port24>(outOutputPosition, Port::OUTPUT, module, Offset::OUT_OUTPUT));
	}

	void appendContextMenu(Menu* menu) override {
	  Offset* offset = dynamic_cast<Offset*>(module);
		assert(offset);
		menu->addChild(new MenuLabel());
		menu->addChild(new DisableOutputLimitMenuItem(offset, "Diable Output Limit"));
	}
};

Model* modelOffset = createModel<Offset, OffsetWidget>("Bogaudio-Offset", "Offset",  "CV offset and scaler", ATTENUATOR_TAG);
