
#include "PEQ14XR.hpp"

void PEQ14XR::Engine::setSampleRate(float sr) {
	for (int i = 0; i < 14; ++i) {
		oscillators[i].setSampleRate(sr);
	}
}

void PEQ14XR::sampleRateChange() {
	float sr = APP->engine->getSampleRate();
	for (int c = 0; c < _channels; ++c) {
		_engines[c]->setSampleRate(sr);
	}
}

void PEQ14XR::addChannel(int c) {
	_engines[c] = new Engine();
	_engines[c]->setSampleRate(APP->engine->getSampleRate());
}

void PEQ14XR::removeChannel(int c) {
	delete _engines[c];
	_engines[c] = NULL;
}

void PEQ14XR::processAlways(const ProcessArgs& args) {
	outputs[OUT_OUTPUT].setChannels(_channels);

	_baseMessage = NULL;
	if (baseConnected()) {
		_baseMessage = fromBase();
	}

	if (expanderConnected()) {
		if (_baseMessage) {
			// *toExpander() = *_baseMessage;
			_baseMessage->copyTo(toExpander());
		}
		else {
			toExpander()->reset();
		}
	}
}

void PEQ14XR::processChannel(const ProcessArgs& args, int c) {
	if (_baseMessage && _baseMessage->valid) {
		Engine& e = *_engines[c];
		float out = 0.0f;
		for (int i = 0; i < 14; ++i) {
			e.oscillators[i].setFrequency(_baseMessage->frequencies[c][i]);

			float db = _baseMessage->levels[c][i];
			db *= 0.2f;
			db = std::max(0.0f, std::min(1.0f, db));
			db = 1.0f - db;
			db *= Amplifier::minDecibels;
			e.amplifiers[i].setLevel(db);

			out += e.amplifiers[i].next(e.oscillators[i].next());
		}
		outputs[OUT_OUTPUT].setVoltage(_saturator.next(out), c);
	}
	else {
		outputs[OUT_OUTPUT].setVoltage(0.0f, c);
	}
}

struct PEQ14XRWidget : ModuleWidget {
	static constexpr int hp = 5;

	PEQ14XRWidget(PEQ14XR* module) {
		setModule(module);
		box.size = Vec(RACK_GRID_WIDTH * hp, RACK_GRID_HEIGHT);

		{
			SvgPanel *panel = new SvgPanel();
			panel->box.size = box.size;
			panel->setBackground(APP->window->loadSvg(asset::plugin(pluginInstance, "res/PEQ14XR.svg")));
			addChild(panel);
		}

		addChild(createWidget<ScrewSilver>(Vec(0, 0)));
		addChild(createWidget<ScrewSilver>(Vec(box.size.x - 15, 365)));

		// generated by svg_widgets.rb
		auto outOutputPosition = Vec(25.5, 322.0);
		// end generated by svg_widgets.rb

		addOutput(createOutput<Port24>(outOutputPosition, module, PEQ14XR::OUT_OUTPUT));
	}
};

Model* modelPEQ14XR = createModel<PEQ14XR, PEQ14XRWidget>("Bogaudio-PEQ14XR", "PEQ14XR", "PEQ14 resynthesizer expander", "Filter", "Vocoder", "Expander", "Polyphonic");
