#include "ShaperCore.hpp"

struct ShaperPlus : Module {
	enum ParamIds {
		ATTACK_PARAM,
		ON_PARAM,
		DECAY_PARAM,
		OFF_PARAM,
		ENV_PARAM,
		SIGNAL_PARAM,
		TRIGGER_PARAM,
		SPEED_PARAM,
		LOOP_PARAM,
		NUM_PARAMS
	};
	enum InputIds {
		SIGNAL_INPUT,
		TRIGGER_INPUT,
		ATTACK_INPUT,
		ON_INPUT,
		DECAY_INPUT,
		OFF_INPUT,
		ENV_INPUT,
		SIGNALCV_INPUT,
		NUM_INPUTS
	};
	enum OutputIds {
		SIGNAL_OUTPUT,
		ENV_OUTPUT,
		INV_OUTPUT,
		TRIGGER_OUTPUT,
		ATTACK_OUTPUT,
		ON_OUTPUT,
		DECAY_OUTPUT,
		OFF_OUTPUT,
		NUM_OUTPUTS
	};
	enum LightIds {
		ATTACK_LIGHT,
		ON_LIGHT,
		DECAY_LIGHT,
		OFF_LIGHT,
		NUM_LIGHTS
	};

	enum Stage {
		STOPPED_STAGE,
		ATTACK_STAGE,
		ON_STAGE,
		DECAY_STAGE,
		OFF_STAGE
	};

	ShaperCore _core;

	ShaperPlus() : Module(
		NUM_PARAMS,
		NUM_INPUTS,
		NUM_OUTPUTS,
		NUM_LIGHTS
	)
	, _core(
		params[ATTACK_PARAM],
		params[ON_PARAM],
		params[DECAY_PARAM],
		params[OFF_PARAM],
		params[ENV_PARAM],
		params[SIGNAL_PARAM],
		params[TRIGGER_PARAM],
		params[SPEED_PARAM],
		params[LOOP_PARAM],

		inputs[SIGNAL_INPUT],
		inputs[TRIGGER_INPUT],
		&inputs[ATTACK_INPUT],
		&inputs[ON_INPUT],
		&inputs[DECAY_INPUT],
		&inputs[OFF_INPUT],
		&inputs[ENV_INPUT],
		&inputs[SIGNALCV_INPUT],

		outputs[SIGNAL_OUTPUT],
		outputs[ENV_OUTPUT],
		outputs[INV_OUTPUT],
		outputs[TRIGGER_OUTPUT],
		&outputs[ATTACK_OUTPUT],
		&outputs[ON_OUTPUT],
		&outputs[DECAY_OUTPUT],
		&outputs[OFF_OUTPUT],

		lights[ATTACK_LIGHT],
		lights[ON_LIGHT],
		lights[DECAY_LIGHT],
		lights[OFF_LIGHT]
	)
	{
		reset();
	}

	virtual void reset() override {
		_core.reset();
	}

	virtual void step() override {
		_core.step();
	}
};

ShaperPlusWidget::ShaperPlusWidget() {
	ShaperPlus *module = new ShaperPlus();
	setModule(module);
	box.size = Vec(RACK_GRID_WIDTH * 15, RACK_GRID_HEIGHT);

	{
		SVGPanel *panel = new SVGPanel();
		panel->box.size = box.size;
		panel->setBackground(SVG::load(assetPlugin(plugin, "res/ShaperPlus.svg")));
		addChild(panel);
	}

	addChild(createScrew<ScrewSilver>(Vec(15, 0)));
	addChild(createScrew<ScrewSilver>(Vec(box.size.x - 30, 0)));
	addChild(createScrew<ScrewSilver>(Vec(15, 365)));
	addChild(createScrew<ScrewSilver>(Vec(box.size.x - 30, 365)));

	// generated by svg_widgets.rb
	auto attackParamPosition = Vec(29.08, 33.08);
	auto triggerParamPosition = Vec(89.04, 43.04);
	auto onParamPosition = Vec(29.08, 89.08);
	auto speedParamPosition = Vec(118.9, 97.9);
	auto decayParamPosition = Vec(29.08, 145.08);
	auto loopParamPosition = Vec(118.9, 153.9);
	auto offParamPosition = Vec(29.08, 201.08);
	auto envParamPosition = Vec(82.38, 257.08);
	auto signalParamPosition = Vec(82.38, 313.08);

	auto triggerInputPosition = Vec(114.0, 40.0);
	auto attackInputPosition = Vec(152.0, 40.0);
	auto onInputPosition = Vec(152.0, 96.0);
	auto decayInputPosition = Vec(152.0, 152.0);
	auto offInputPosition = Vec(152.0, 208.0);
	auto envInputPosition = Vec(152.0, 264.0);
	auto signalInputPosition = Vec(11.5, 320.0);
	auto signalcvInputPosition = Vec(152.0, 320.0);

	auto attackOutputPosition = Vec(189.0, 40.0);
	auto onOutputPosition = Vec(189.0, 96.0);
	auto decayOutputPosition = Vec(189.0, 152.0);
	auto offOutputPosition = Vec(189.0, 208.0);
	auto envOutputPosition = Vec(11.5, 264.0);
	auto invOutputPosition = Vec(40.5, 264.0);
	auto triggerOutputPosition = Vec(189.0, 264.0);
	auto signalOutputPosition = Vec(40.5, 320.0);

	auto attackLightPosition = Vec(12.0, 80.0);
	auto onLightPosition = Vec(12.0, 121.0);
	auto decayLightPosition = Vec(12.0, 189.0);
	auto offLightPosition = Vec(12.0, 237.0);
	// end generated by svg_widgets.rb

	addParam(createParam<Knob38>(attackParamPosition, module, ShaperPlus::ATTACK_PARAM, 0.0, 1.0, 0.12));
	addParam(createParam<Knob38>(onParamPosition, module, ShaperPlus::ON_PARAM, 0.0, 1.0, 0.32));
	addParam(createParam<Knob38>(decayParamPosition, module, ShaperPlus::DECAY_PARAM, 0.0, 1.0, 0.32));
	addParam(createParam<Knob38>(offParamPosition, module, ShaperPlus::OFF_PARAM, 0.0, 1.0, 0.07));
	addParam(createParam<Knob38>(envParamPosition, module, ShaperPlus::ENV_PARAM, 0.0, 1.0, 1.0));
	addParam(createParam<Knob38>(signalParamPosition, module, ShaperPlus::SIGNAL_PARAM, 0.0, 1.0, 0.5));

	addParam(createParam<Button18>(triggerParamPosition, module, ShaperPlus::TRIGGER_PARAM, 0.0, 1.0, 0.0));
	addInput(createInput<PJ301MPort>(triggerInputPosition, module, ShaperPlus::TRIGGER_INPUT));

	addParam(createParam<CKSS>(speedParamPosition, module, ShaperPlus::SPEED_PARAM, 0.0, 1.0, 1.0));
	addParam(createParam<CKSS>(loopParamPosition, module, ShaperPlus::LOOP_PARAM, 0.0, 1.0, 1.0));
	addOutput(createOutput<PJ301MPort>(triggerOutputPosition, module, ShaperPlus::TRIGGER_OUTPUT));

	addOutput(createOutput<PJ301MPort>(envOutputPosition, module, ShaperPlus::ENV_OUTPUT));
	addOutput(createOutput<PJ301MPort>(invOutputPosition, module, ShaperPlus::INV_OUTPUT));

	addInput(createInput<PJ301MPort>(signalInputPosition, module, ShaperPlus::SIGNAL_INPUT));
	addOutput(createOutput<PJ301MPort>(signalOutputPosition, module, ShaperPlus::SIGNAL_OUTPUT));

	addInput(createInput<PJ301MPort>(attackInputPosition, module, ShaperPlus::ATTACK_INPUT));
	addInput(createInput<PJ301MPort>(onInputPosition, module, ShaperPlus::ON_INPUT));
	addInput(createInput<PJ301MPort>(decayInputPosition, module, ShaperPlus::DECAY_INPUT));
	addInput(createInput<PJ301MPort>(offInputPosition, module, ShaperPlus::OFF_INPUT));
	addInput(createInput<PJ301MPort>(envInputPosition, module, ShaperPlus::ENV_INPUT));
	addInput(createInput<PJ301MPort>(signalcvInputPosition, module, ShaperPlus::SIGNALCV_INPUT));

	addOutput(createOutput<PJ301MPort>(attackOutputPosition, module, ShaperPlus::ATTACK_OUTPUT));
	addOutput(createOutput<PJ301MPort>(onOutputPosition, module, ShaperPlus::ON_OUTPUT));
	addOutput(createOutput<PJ301MPort>(decayOutputPosition, module, ShaperPlus::DECAY_OUTPUT));
	addOutput(createOutput<PJ301MPort>(offOutputPosition, module, ShaperPlus::OFF_OUTPUT));

	addChild(createLight<TinyLight<GreenLight>>(attackLightPosition, module, ShaperPlus::ATTACK_LIGHT));
	addChild(createLight<TinyLight<GreenLight>>(onLightPosition, module, ShaperPlus::ON_LIGHT));
	addChild(createLight<TinyLight<GreenLight>>(decayLightPosition, module, ShaperPlus::DECAY_LIGHT));
	addChild(createLight<TinyLight<GreenLight>>(offLightPosition, module, ShaperPlus::OFF_LIGHT));
}
